### ISSUE TITLE
Leetcode 992 Subarray with k different integers

### ISSUE THREAD

**Issue by sparshgarg23** [kamyu104/LeetCode-Solutions#88]
In the problem it is mentioned that the subarray doesn't have to be distinct.I recieved a problem in my coding interview shown below
https://leetcode.com/discuss/interview-question/278341/Uber-phone-interview-Number-of-distinct-subarrays-with-at-most-k-odd-elements/265140
After reading the problem description and the subarray with k different integers,can we extend it to take into consideration odd elements.I tried doing that but I am getting 0 as my answer.Any suggestions will be welcome

**Comment by kamyu104** [comment]
1. No, they are something different, because of **distinct subarray**.
2. There are at most **O(n^2)** distinct subarrays if all elemtents are distinct odds and **k** is **n**, thes the worst case of complexity would be at least **O(n^2)**.
3. Most solutions in your link are **O(n^3)**, which is not really **O(n^2)** as they claimed
4. The best way to run in **O(n^2)** may be like **zed_b** and **TheSithPadawan** said in the link:
    - Find all distinct substrings via **suffix tree** by using **Ukkonen's algorithm** in **O(n)**
    - Count prefix array of odd count in **O(n)**
     - Use the prefix array to count if each substring is valid in **O(n^2)**
