### ISSUE TITLE
Leetcode 377 combination sum iv

### ISSUE THREAD

**Issue by sparshgarg23** [kamyu104/LeetCode-Solutions#94]
Hi,I was running your solution for the above mentioned problem.It seems that if we create a vector of integers to represent then we get the following error:
"Runtime error signed integer overflow <large number addition cannot be represented by int?
The error goes away if we use unsigned integer representation.
Also can you please explain the logic behind the solution

**Comment by kamyu104** [comment]
1. Thanks for your reminding.
2. We denote the number of combination of i as dp[i]
- The idea is to get the number of combination of each interger i from 0 to target, 
- For each dp[i], we can get dp[i] = sum(dp[i - num] for each num in nums and num <= i).
3. Since dp[i] may exceed the max of int32, it is required to use uint32_t or uint64_t to count the number based on the input range.
